### ISSUE TITLE
 env: ruby_executable_hooks: No such file or directory (While Package project)

### ISSUE THREAD

**Issue by cppgod17** [cleveradssolutions/CAS-Unreal#2]
Привет, пытаюсь собрать проект под IOS, выдает данную ошибку, собираю проект через винду(что девелопмент, что shipping не собираются), так всегда собирал(так собирают наверное 90% разработчиков(CI/CD итп) https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/Mobile/iOS/Windows/ с предыдущей версией проблем не было, 
![image](https://github.com/cleveradssolutions/CAS-Unreal/assets/46503223/1e9b1ee4-5ffa-449b-ab64-081987a74337)
[Logs.zip](https://github.com/cleveradssolutions/CAS-Unreal/files/14072319/Logs.zip)
выше логи

**Comment by cppgod17** [comment]
Этот ruby_executable_hooks тоже установил но все равно не работает

**Comment by Str4tos** [comment]
Добрый день. Спасибо за описание проблемы.

Мы проверим и сделаем необходимые изменения в следующем обновлении.

~~На данный момент сборка IOS package поддерживается только из MAC OS.~~  
Сборка IOS package поддерживается из Windows через Remote MAC OS.

**Comment by Str4tos** [comment]
@cppgod17 Расскажите немного подробнее. 
Вы используете Remote Mac для сборки из Windows? На этом Mac установлен CocoaPods?

**Comment by Str4tos** [comment]
This error occurs due to an incorrect installation of the Ruby Version Manager (RVM).  
We recommend using the system version of Ruby, which does not require RVM.  
Please open a new issue if the problem arises again.
