### ISSUE TITLE
Duplicate class error

### ISSUE THREAD

**Issue by NursultanNazarov** [cleveradssolutions/CAS-Unreal#3]
Hi. I used the latest commit and having error when packaging for Android. Error message is: A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
> Duplicate class com.google.android.gms.games.AcievenmentsClient found in modules jetified-play-services- games-23.1.0.........

**Comment by Str4tos** [comment]
Hi @NursultanNazarov, thank you for raising the issue.

This issue is fixed in the CAS Unreal plugin 3.7.3.1 update.  
If you encounter any other issues, feel free to open the new one.

**Comment by NursultanNazarov** [comment]
thanks
